-- Isolated PostgreSQL fixture. No production data or credentials.
-- Estimate columns / constraints and RLS mirror the 2026-10-01 live inspection;
-- unrelated master tables are reduced to keys used by estimate foreign keys.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN CREATE ROLE authenticated; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN CREATE ROLE anon; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='service_role') THEN CREATE ROLE service_role; END IF;
END $$;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('request.jwt.claim.sub',true),'')::uuid;
$$;
CREATE TABLE public.office_staff (
  id integer PRIMARY KEY, name text, auth_user_id uuid, role text, is_approver boolean DEFAULT false
);
CREATE TABLE public."Customers" (id bigint PRIMARY KEY);
CREATE TABLE public."Projects" (id bigint PRIMARY KEY);
CREATE TABLE public."Workers" (id bigint PRIMARY KEY);
CREATE TABLE public.estimates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz, estimate_number text NOT NULL UNIQUE,
  customer_id bigint NOT NULL REFERENCES public."Customers", project_id bigint REFERENCES public."Projects",
  created_by bigint REFERENCES public."Workers", title text NOT NULL, site_location text, work_period text,
  issue_date date NOT NULL DEFAULT CURRENT_DATE, valid_until date,
  payment_terms text NOT NULL DEFAULT '従来通り', notes text,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','pending','approved','returned','submitted','ordered','lost')),
  tax_rate numeric NOT NULL DEFAULT 0.10, show_fixed_fees boolean NOT NULL DEFAULT true,
  show_net boolean NOT NULL DEFAULT true, show_subtotals boolean NOT NULL DEFAULT false,
  stamp_header text NOT NULL DEFAULT 'company' CHECK (stamp_header IN ('company','representative','none')),
  show_approver boolean NOT NULL DEFAULT false, total_with_tax numeric, net_calc_type text DEFAULT 'auto',
  net_perc numeric DEFAULT 95, net_amount numeric, customer_honorific text DEFAULT '御中',
  staff_id integer REFERENCES public.office_staff ON DELETE SET NULL,
  approved_by text, approved_at timestamptz, returned_reason text, lost_reason text,
  approver_staff_id integer REFERENCES public.office_staff ON DELETE SET NULL
);
CREATE TABLE public.estimate_sheets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  estimate_id bigint NOT NULL REFERENCES public.estimates ON DELETE CASCADE,
  sort_order integer NOT NULL DEFAULT 1, title text, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.estimate_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(),
  estimate_id bigint NOT NULL REFERENCES public.estimates ON DELETE CASCADE,
  parent_id bigint REFERENCES public.estimate_items ON DELETE CASCADE,
  sort_order integer NOT NULL DEFAULT 0,
  item_type text NOT NULL CHECK (item_type IN ('category','item','subtotal','fixed')),
  category_symbol text, name text NOT NULL, spec text, quantity numeric, unit text, unit_price numeric,
  amount numeric, note text,
  sheet_id uuid REFERENCES public.estimate_sheets ON DELETE CASCADE,
  linked_sheet_id uuid REFERENCES public.estimate_sheets ON DELETE SET NULL,
  linked_category_item_id bigint REFERENCES public.estimate_items ON DELETE SET NULL
);
CREATE FUNCTION public.calc_estimate_item_amount() RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$
BEGIN
  IF NEW.item_type='item' AND NEW.amount IS NULL AND NEW.quantity IS NOT NULL AND NEW.unit_price IS NOT NULL THEN
    NEW.amount := NEW.quantity * NEW.unit_price;
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_calc_estimate_item_amount BEFORE INSERT OR UPDATE OF quantity,unit_price ON public.estimate_items
FOR EACH ROW EXECUTE FUNCTION public.calc_estimate_item_amount();
GRANT USAGE ON SCHEMA public,auth TO authenticated,anon;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO authenticated;
INSERT INTO public."Customers" VALUES (1);
INSERT INTO public."Projects" VALUES (1);
INSERT INTO public.office_staff VALUES
 (1,'Creator','00000000-0000-0000-0000-000000000001','office',false),
 (2,'Approver','00000000-0000-0000-0000-000000000002','office',true),
 (3,'Other','00000000-0000-0000-0000-000000000003','office',true),
 (4,'Admin','00000000-0000-0000-0000-000000000004','admin',true),
 (5,'Viewer','00000000-0000-0000-0000-000000000005','viewer',false);
