-- =========================================================
-- 塗料データベース 物理設計
-- 概念設計 → 論理設計 を踏まえた Supabase(PostgreSQL) 向け DDL
-- 命名規則: snake_case（estimates系の新しめのテーブルに合わせる）
-- 論理削除: deleted_at 方式（estimates テーブルと同じ）
-- RLS方針: Projects/ProjectTasks 等と同じ「office/adminが全操作、
--           worker/viewerは参照のみ」パターンに合わせる
-- =========================================================


-- 1. メーカーマスタ
create table public.paint_manufacturers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);
comment on table public.paint_manufacturers is '塗料メーカーマスタ';


-- 2. 工程区分マスタ
create table public.paint_process_roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer,
  created_at timestamptz not null default now()
);
comment on table public.paint_process_roles is '工程区分マスタ（下塗/中塗/上塗等）';


-- 3. 塗料製品マスタ
create table public.paint_products (
  id bigint generated by default as identity primary key,
  manufacturer_id bigint not null references public.paint_manufacturers(id),
  process_role_id bigint not null references public.paint_process_roles(id),
  name text not null,
  product_code text,
  standard_usage_rate numeric,
  usage_rate_unit text,
  recoat_interval_standard_days integer,
  recoat_interval_max_days integer,
  dilution_rate text,
  pot_life text,
  drying_time text,
  reference_price numeric,
  reference_price_unit text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.paint_products is '塗料製品マスタ';
comment on column public.paint_products.standard_usage_rate is '標準使用量（メーカー公表値）';
comment on column public.paint_products.recoat_interval_standard_days is '上塗間隔 標準値（日換算）';
comment on column public.paint_products.recoat_interval_max_days is '上塗間隔 許容上限（日換算）';
comment on column public.paint_products.dilution_rate is '希釈率（自由記述、例: 5〜10%(23℃)）';
comment on column public.paint_products.reference_price is '未購入品の参考単価（実仕入がある場合はPurchaseRecordsを優先参照）';

create index idx_paint_products_manufacturer_id on public.paint_products(manufacturer_id);
create index idx_paint_products_process_role_id on public.paint_products(process_role_id);


-- 4. 分類軸マスタ
create table public.paint_classification_axes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);
comment on table public.paint_classification_axes is '塗料分類軸マスタ（系統/樹脂/水性溶剤区分/液性/JIS認証等の「軸」）';


-- 5. 分類タグ値マスタ
create table public.paint_classification_tags (
  id bigint generated by default as identity primary key,
  axis_id bigint not null references public.paint_classification_axes(id),
  value text not null,
  sort_order integer,
  created_at timestamptz not null default now(),
  unique (axis_id, value)
);
comment on table public.paint_classification_tags is '塗料分類タグ値マスタ（軸ごとの具体的な値）';
create index idx_paint_classification_tags_axis_id on public.paint_classification_tags(axis_id);


-- 6. 製品×タグ 中間テーブル
create table public.paint_product_tags (
  product_id bigint not null references public.paint_products(id) on delete cascade,
  tag_id bigint not null references public.paint_classification_tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (product_id, tag_id)
);
comment on table public.paint_product_tags is '塗料製品と分類タグの多対多紐付け';
create index idx_paint_product_tags_tag_id on public.paint_product_tags(tag_id);


-- 7. 塗装仕様（組み合わせレシピ）マスタ
create table public.coating_systems (
  id bigint generated by default as identity primary key,
  name text not null,
  target_use text,
  description text,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.coating_systems is '塗装仕様（組み合わせレシピ）マスタ。例: Rc-Ⅰ、住宅屋根用フッ素系';
comment on column public.coating_systems.target_use is '対象用途の説明（自由記述。将来 paint_classification_tags の「用途系統」軸への置き換えを検討）';


-- 8. 塗装仕様の構成行
create table public.coating_system_steps (
  id bigint generated by default as identity primary key,
  coating_system_id bigint not null references public.coating_systems(id) on delete cascade,
  step_order integer not null,
  process_role_id bigint not null references public.paint_process_roles(id),
  product_id bigint not null references public.paint_products(id),
  created_at timestamptz not null default now(),
  unique (coating_system_id, step_order)
);
comment on table public.coating_system_steps is '塗装仕様の構成行（工程順に採用する製品を定義）';
create index idx_coating_system_steps_product_id on public.coating_system_steps(product_id);


-- 9. 既存 PurchaseRecords への連携列追加
alter table public."PurchaseRecords"
  add column paint_product_id bigint references public.paint_products(id);
comment on column public."PurchaseRecords".paint_product_id is '塗料製品マスタへの紐付け（新規レコードから設定。過去分はitem_nameのまま）';
create index idx_purchase_records_paint_product_id on public."PurchaseRecords"(paint_product_id);


-- =========================================================
-- RLS
-- =========================================================

alter table public.paint_manufacturers enable row level security;
alter table public.paint_process_roles enable row level security;
alter table public.paint_products enable row level security;
alter table public.paint_classification_axes enable row level security;
alter table public.paint_classification_tags enable row level security;
alter table public.paint_product_tags enable row level security;
alter table public.coating_systems enable row level security;
alter table public.coating_system_steps enable row level security;

create policy paint_manufacturers_office_all on public.paint_manufacturers
  for all using (is_admin() or current_staff_role() = 'office')
  with check (is_admin() or current_staff_role() = 'office');
create policy paint_manufacturers_select_worker_viewer on public.paint_manufacturers
  for select using (current_staff_role() = any (array['worker', 'viewer']));

create policy paint_process_roles_office_all on public.paint_process_roles
  for all using (is_admin() or current_staff_role() = 'office')
  with check (is_admin() or current_staff_role() = 'office');
create policy paint_process_roles_select_worker_viewer on public.paint_process_roles
  for select using (current_staff_role() = any (array['worker', 'viewer']));

create policy paint_products_office_all on public.paint_products
  for all using (is_admin() or current_staff_role() = 'office')
  with check (is_admin() or current_staff_role() = 'office');
create policy paint_products_select_worker_viewer on public.paint_products
  for select using (current_staff_role() = any (array['worker', 'viewer']));

create policy paint_classification_axes_office_all on public.paint_classification_axes
  for all using (is_admin() or current_staff_role() = 'office')
  with check (is_admin() or current_staff_role() = 'office');
create policy paint_classification_axes_select_worker_viewer on public.paint_classification_axes
  for select using (current_staff_role() = any (array['worker', 'viewer']));

create policy paint_classification_tags_office_all on public.paint_classification_tags
  for all using (is_admin() or current_staff_role() = 'office')
  with check (is_admin() or current_staff_role() = 'office');
create policy paint_classification_tags_select_worker_viewer on public.paint_classification_tags
  for select using (current_staff_role() = any (array['worker', 'viewer']));

create policy paint_product_tags_office_all on public.paint_product_tags
  for all using (is_admin() or current_staff_role() = 'office')
  with check (is_admin() or current_staff_role() = 'office');
create policy paint_product_tags_select_worker_viewer on public.paint_product_tags
  for select using (current_staff_role() = any (array['worker', 'viewer']));

create policy coating_systems_office_all on public.coating_systems
  for all using (is_admin() or current_staff_role() = 'office')
  with check (is_admin() or current_staff_role() = 'office');
create policy coating_systems_select_worker_viewer on public.coating_systems
  for select using (current_staff_role() = any (array['worker', 'viewer']));

create policy coating_system_steps_office_all on public.coating_system_steps
  for all using (is_admin() or current_staff_role() = 'office')
  with check (is_admin() or current_staff_role() = 'office');
create policy coating_system_steps_select_worker_viewer on public.coating_system_steps
  for select using (current_staff_role() = any (array['worker', 'viewer']));


-- =========================================================
-- 初期マスタデータ
-- =========================================================

insert into public.paint_process_roles (name, sort_order) values
  ('防食下地', 1),
  ('下塗', 2),
  ('中塗', 3),
  ('上塗', 4),
  ('ジンクリッチ', 5);

insert into public.paint_classification_axes (name) values
  ('用途系統'),
  ('樹脂種別'),
  ('水性/溶剤区分'),
  ('液性'),
  ('JIS認証');

insert into public.paint_classification_tags (axis_id, value, sort_order)
select id, v.value, v.sort_order
from public.paint_classification_axes, lateral (
  values
    ('土木構造物用', 1), ('住宅外装用', 2), ('住宅屋根用', 3), ('内装用', 4), ('鉄部用', 5)
) as v(value, sort_order)
where name = '用途系統';

insert into public.paint_classification_tags (axis_id, value, sort_order)
select id, v.value, v.sort_order
from public.paint_classification_axes, lateral (
  values
    ('アクリル', 1), ('ウレタン', 2), ('シリコン', 3), ('フッ素', 4), ('無機系', 5)
) as v(value, sort_order)
where name = '樹脂種別';

insert into public.paint_classification_tags (axis_id, value, sort_order)
select id, v.value, v.sort_order
from public.paint_classification_axes, lateral (
  values
    ('水性系', 1), ('弱溶剤系', 2), ('強溶剤系', 3)
) as v(value, sort_order)
where name = '水性/溶剤区分';

insert into public.paint_classification_tags (axis_id, value, sort_order)
select id, v.value, v.sort_order
from public.paint_classification_axes, lateral (
  values
    ('1液', 1), ('2液', 2)
) as v(value, sort_order)
where name = '液性';

insert into public.paint_classification_tags (axis_id, value, sort_order)
select id, v.value, v.sort_order
from public.paint_classification_axes, lateral (
  values
    ('JIS取得', 1), ('JIS非該当', 2)
) as v(value, sort_order)
where name = 'JIS認証';
