-- 塗料データベース拡張（日本ペイント設計価格表への対応）
--   1. 材工価格（円/㎡）を仕様の価格分岐として保持する coating_system_variants
--   2. JIS に加え JASS 認証を規格番号つきで保持する paint_standards / paint_product_standards
--   3. 略号（SOP, VP, DP, EP 等）を仕様に紐づける paint_abbreviations / coating_system_abbreviations
--   4. 仕様の代表製品（primary_product_id）で「この製品の下塗りは何か」を辿れるようにする
--   5. ホルムアルデヒド放散等級（F☆☆☆☆）を製品属性として追加
-- 旧「JIS認証」分類軸は paint_standards に役割を移すため廃止する。

-- ---------------------------------------------------------------------------
-- 1. 材工価格（仕様の価格分岐）
-- ---------------------------------------------------------------------------
-- 価格表では同一仕様でも「仕上げの種類 × 施工方法 × 目地 × 面積区分」で
-- 材工価格・工程数・JIS A 6909 適合が変わる。分岐軸はいずれも任意（NULL可）。
create table if not exists public.coating_system_variants (
  id bigint generated by default as identity primary key,
  coating_system_id bigint not null references public.coating_systems(id) on delete cascade,
  finish_type text,                     -- 仕上げの種類（平滑・ゆず肌・凸部処理 等）
  application_method text,              -- 施工方法（吹付け・ローラー 等）
  joint_type text,                      -- 目地（有・無 等）
  area_min numeric,                     -- 適用面積の下限（㎡）
  area_max numeric,                     -- 適用面積の上限（㎡）
  material_labor_price numeric,         -- 材工価格（円/㎡）
  process_count integer,                -- 工程数（価格分岐ごとに異なるため転記値）
  jis_a6909_compliant boolean not null default false, -- JIS A 6909 適合（㋓表示）
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists coating_system_variants_system_idx
  on public.coating_system_variants (coating_system_id);

comment on table public.coating_system_variants is '塗装仕様の価格分岐（材工価格・工程数・JIS A 6909適合）';
comment on column public.coating_system_variants.material_labor_price is '材工価格（円/㎡）';
comment on column public.coating_system_variants.process_count is '工程数。coat_count の合計では導出できないため価格表からの転記値を保持する';

-- ---------------------------------------------------------------------------
-- 2. 規格認証（JIS / JASS）
-- ---------------------------------------------------------------------------
create table if not exists public.paint_standards (
  id bigint generated by default as identity primary key,
  standard_type text not null check (standard_type in ('JIS', 'JASS')),
  code text not null,                   -- 例: 'A 6909', '18 M-109'
  name text,                            -- 例: '建築用仕上塗材'
  is_abolished boolean not null default false, -- 廃止規格か
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (standard_type, code)
);

comment on table public.paint_standards is 'JIS / JASS 規格マスタ（規格番号つき）';

create table if not exists public.paint_product_standards (
  product_id bigint not null references public.paint_products(id) on delete cascade,
  standard_id bigint not null references public.paint_standards(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (product_id, standard_id)
);

comment on table public.paint_product_standards is '製品と規格認証の対応（多対多）';

-- ---------------------------------------------------------------------------
-- 3. 略号（SOP / VP / DP / EP 等）
-- ---------------------------------------------------------------------------
-- 略号は製品ではなく仕様（工程の組み合わせ）に付く。1仕様に複数付くこともある
-- （例：「略号：EP-Si・EP-CS」）ため中間テーブルで持つ。
create table if not exists public.paint_abbreviations (
  id bigint generated by default as identity primary key,
  code text not null unique,            -- 'EP-G' 等
  name text,                            -- '水性つや有エマルションペイント塗り' 等
  description text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.paint_abbreviations is '塗装仕様の略号マスタ（公共建築工事標準仕様書等）';

create table if not exists public.coating_system_abbreviations (
  coating_system_id bigint not null references public.coating_systems(id) on delete cascade,
  abbreviation_id bigint not null references public.paint_abbreviations(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (coating_system_id, abbreviation_id)
);

comment on table public.coating_system_abbreviations is '仕様と略号の対応（多対多）';

-- ---------------------------------------------------------------------------
-- 4. 既存テーブルの拡張
-- ---------------------------------------------------------------------------
-- 代表製品。「水性ケンエースグロス（EP-G）の下塗りは水性カチオンシーラー透明」を
-- 製品 → 代表仕様 → 工程 と辿って引けるようにする。
alter table public.coating_systems
  add column if not exists primary_product_id bigint references public.paint_products(id);

create index if not exists coating_systems_primary_product_idx
  on public.coating_systems (primary_product_id);

comment on column public.coating_systems.primary_product_id is 'この仕様を代表する製品（上塗材など）。製品から関連する下塗材を辿るために使う';

-- 塗回数。見積の数量計算に使う。工程数（process_count）の導出には使わない。
alter table public.coating_system_steps
  add column if not exists coat_count integer not null default 1;

comment on column public.coating_system_steps.coat_count is '当該工程の塗回数。見積計算用';

-- ホルムアルデヒド放散等級（F☆☆☆☆ 等）
alter table public.paint_products
  add column if not exists formaldehyde_grade text;

comment on column public.paint_products.formaldehyde_grade is 'ホルムアルデヒド放散等級（例: F☆☆☆☆）';

-- ---------------------------------------------------------------------------
-- 5. 旧「JIS認証」分類軸の廃止と paint_standards への引き継ぎ
-- ---------------------------------------------------------------------------
-- 「JIS取得」タグが付いた製品は規格番号が未確認のため、暫定行に紐づけて情報を保全する。
-- 「JIS非該当」は新スキーマでは「紐付けなし」で表現するため引き継がない。
insert into public.paint_standards (standard_type, code, name, is_abolished, sort_order)
values ('JIS', '規格番号未確認', 'JIS表示認証品（規格番号は要確認）', false, 999)
on conflict (standard_type, code) do nothing;

insert into public.paint_product_standards (product_id, standard_id)
select pt.product_id, s.id
from public.paint_product_tags pt
join public.paint_classification_tags t on t.id = pt.tag_id
join public.paint_classification_axes a on a.id = t.axis_id
cross join lateral (
  select id from public.paint_standards
  where standard_type = 'JIS' and code = '規格番号未確認'
) s
where a.name = 'JIS認証' and t.value = 'JIS取得'
on conflict do nothing;

delete from public.paint_product_tags
where tag_id in (
  select t.id from public.paint_classification_tags t
  join public.paint_classification_axes a on a.id = t.axis_id
  where a.name = 'JIS認証'
);

delete from public.paint_classification_tags
where axis_id in (select id from public.paint_classification_axes where name = 'JIS認証');

delete from public.paint_classification_axes where name = 'JIS認証';

-- ---------------------------------------------------------------------------
-- 6. RLS（既存 paint_* テーブルと同じパターン）
-- ---------------------------------------------------------------------------
alter table public.coating_system_variants enable row level security;
alter table public.paint_standards enable row level security;
alter table public.paint_product_standards enable row level security;
alter table public.paint_abbreviations enable row level security;
alter table public.coating_system_abbreviations enable row level security;

drop policy if exists coating_system_variants_office_all on public.coating_system_variants;
create policy coating_system_variants_office_all on public.coating_system_variants
  for all using (is_admin() or current_staff_role() = 'office')
  with check (is_admin() or current_staff_role() = 'office');
drop policy if exists coating_system_variants_select_worker_viewer on public.coating_system_variants;
create policy coating_system_variants_select_worker_viewer on public.coating_system_variants
  for select using (current_staff_role() = any (array['worker', 'viewer']));

drop policy if exists paint_standards_office_all on public.paint_standards;
create policy paint_standards_office_all on public.paint_standards
  for all using (is_admin() or current_staff_role() = 'office')
  with check (is_admin() or current_staff_role() = 'office');
drop policy if exists paint_standards_select_worker_viewer on public.paint_standards;
create policy paint_standards_select_worker_viewer on public.paint_standards
  for select using (current_staff_role() = any (array['worker', 'viewer']));

drop policy if exists paint_product_standards_office_all on public.paint_product_standards;
create policy paint_product_standards_office_all on public.paint_product_standards
  for all using (is_admin() or current_staff_role() = 'office')
  with check (is_admin() or current_staff_role() = 'office');
drop policy if exists paint_product_standards_select_worker_viewer on public.paint_product_standards;
create policy paint_product_standards_select_worker_viewer on public.paint_product_standards
  for select using (current_staff_role() = any (array['worker', 'viewer']));

drop policy if exists paint_abbreviations_office_all on public.paint_abbreviations;
create policy paint_abbreviations_office_all on public.paint_abbreviations
  for all using (is_admin() or current_staff_role() = 'office')
  with check (is_admin() or current_staff_role() = 'office');
drop policy if exists paint_abbreviations_select_worker_viewer on public.paint_abbreviations;
create policy paint_abbreviations_select_worker_viewer on public.paint_abbreviations
  for select using (current_staff_role() = any (array['worker', 'viewer']));

drop policy if exists coating_system_abbreviations_office_all on public.coating_system_abbreviations;
create policy coating_system_abbreviations_office_all on public.coating_system_abbreviations
  for all using (is_admin() or current_staff_role() = 'office')
  with check (is_admin() or current_staff_role() = 'office');
drop policy if exists coating_system_abbreviations_select_worker_viewer on public.coating_system_abbreviations;
create policy coating_system_abbreviations_select_worker_viewer on public.coating_system_abbreviations
  for select using (current_staff_role() = any (array['worker', 'viewer']));
