CREATE TABLE IF NOT EXISTS public."PurchaseRecords" (
    id bigint generated by default as identity primary key,
    date date,
    project_name text,
    supplier text,
    item_name text,
    note text,
    quantity numeric,
    unit text,
    unit_price numeric,
    amount numeric,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS settings to allow open access for this application
ALTER TABLE public."PurchaseRecords" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public."PurchaseRecords"
    FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON public."PurchaseRecords"
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON public."PurchaseRecords"
    FOR UPDATE USING (true);

CREATE POLICY "Enable delete for all users" ON public."PurchaseRecords"
    FOR DELETE USING (true);
