-- 配置表バーチャートのセル（案件×日付）単位のコメント
CREATE TABLE IF NOT EXISTS public."AssignmentCellComments" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES public."Projects"(id) ON DELETE CASCADE,
  date date NOT NULL,
  comment text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT assignment_cell_comments_project_date_key UNIQUE (project_id, date),
  CONSTRAINT assignment_cell_comments_not_blank CHECK (length(btrim(comment)) > 0)
);

CREATE INDEX IF NOT EXISTS assignment_cell_comments_date_idx
  ON public."AssignmentCellComments" (date);

ALTER TABLE public."AssignmentCellComments" ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."AssignmentCellComments" TO authenticated;

-- admin/office フルアクセス、worker/viewerはSELECTのみ（ProjectSuspensionsと同じ方針）
CREATE POLICY "assignment_cell_comments_office_all"
  ON public."AssignmentCellComments"
  FOR ALL TO authenticated
  USING (public.is_admin() OR public.current_staff_role() = 'office')
  WITH CHECK (public.is_admin() OR public.current_staff_role() = 'office');

CREATE POLICY "assignment_cell_comments_select_worker_viewer"
  ON public."AssignmentCellComments"
  FOR SELECT TO authenticated
  USING (public.current_staff_role() IN ('worker', 'viewer'));

COMMENT ON TABLE public."AssignmentCellComments"
  IS '配置表バーチャートのセル（案件×日付）に付けるコメント';
